# Generated by Django 5.2.6 on 2025-09-11 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Lun', 'Lunes'), ('Mar', 'Martes'), ('Mié', 'Miércoles'), ('Jue', 'Jueves'), ('Vie', 'Viernes'), ('Sáb', 'Sábado'), ('Dom', 'Domingo')], max_length=10, unique=True, verbose_name='día de la semana')),
            ],
            options={
                'verbose_name': 'Día',
                'verbose_name_plural': 'Días',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trabajador',
                'verbose_name_plural': 'Trabajadores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=1, verbose_name='posición')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='schedule.day', verbose_name='día')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seats', to='schedule.worker', verbose_name='trabajador')),
            ],
            options={
                'verbose_name': 'Asiento',
                'verbose_name_plural': 'Asientos',
                'ordering': ['day', 'position'],
                'unique_together': {('day', 'position')},
            },
        ),
    ]
