# Generated by Django 5.2.5 on 2025-09-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='nombre de habilidad')),
                ('level', models.PositiveSmallIntegerField(default=1, verbose_name='nivel (1-5)')),
                ('workers', models.ManyToManyField(blank=True, related_name='skills', to='schedule.worker')),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades',
                'ordering': ['name'],
            },
        ),
    ]
