# Generated by Django 5.2.5 on 2025-09-30 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='level',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='workers',
        ),
        migrations.CreateModel(
            name='WorkerSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=1, verbose_name='nivel (1-5)')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.skill')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.worker')),
            ],
            options={
                'verbose_name': 'Habilidad del trabajador',
                'verbose_name_plural': 'Habilidades de trabajadores',
                'unique_together': {('worker', 'skill')},
            },
        ),
    ]
