# Generated by Django 5.2.5 on 2025-09-30 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_remove_skill_level_remove_skill_workers_workerskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='fecha')),
                ('performance', models.CharField(max_length=100, verbose_name='desempeño')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='salario calculado')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='schedule.worker')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['-date'],
            },
        ),
    ]
